"""Public synchronous API for the unofficial Better Colab client."""

from better_colab.client import BetterColabClient
from better_colab.errors import BetterColabError, ExitCode
from better_colab.models import (
    ArgumentSpec,
    Artifact,
    BatchResult,
    BatchState,
    BatchWaitResult,
    CapabilitiesResult,
    CommandCapability,
    CompletionSource,
    ControllerStatus,
    ControllerStopResult,
    DoctorResult,
    ErrorDetail,
    ExecutionState,
    ExecutionListResult,
    ExecutionResult,
    ExecutionSummary,
    ExecutionTransitionSummary,
    ExecutionWaitResult,
    HealthResult,
    Limits,
    NotebookCell,
    NotebookCellSummary,
    NotebookCellsResult,
    NotebookIdsResult,
    NotebookWriteResult,
    OutputEvent,
    OutputPage,
    PruneResult,
    SessionHealthResult,
    SessionListResult,
    SessionStopResult,
    SessionSummary,
    SourceProvenance,
)

__all__ = [
    "ArgumentSpec",
    "Artifact",
    "BatchResult",
    "BatchState",
    "BatchWaitResult",
    "BetterColabClient",
    "BetterColabError",
    "CapabilitiesResult",
    "CommandCapability",
    "CompletionSource",
    "ControllerStatus",
    "ControllerStopResult",
    "DoctorResult",
    "ErrorDetail",
    "ExecutionState",
    "ExecutionListResult",
    "ExecutionResult",
    "ExecutionSummary",
    "ExecutionTransitionSummary",
    "ExecutionWaitResult",
    "ExitCode",
    "HealthResult",
    "Limits",
    "NotebookCell",
    "NotebookCellSummary",
    "NotebookCellsResult",
    "NotebookIdsResult",
    "NotebookWriteResult",
    "OutputEvent",
    "OutputPage",
    "PruneResult",
    "SessionHealthResult",
    "SessionListResult",
    "SessionStopResult",
    "SessionSummary",
    "SourceProvenance",
]
